var password;
var passwords;
password = "6523fghajk";
console.log(password);
password = true;
console.log(password);
password = 64523;
console.log(password);
passwords = ["agsh", 6523, false];
console.log(passwords);
